DEFAULT: 20
ARMORER: -1
BUTCHER: -1
CARTOGRAPHER: -1
CLERIC: -1
FARMER: -1
FISHERMAN: -1
FLETCHER: -1
LEATHERWORKER: -1
LIBRARIAN: 0
MASON: -1
SHEPHERD: -1
TOOLSMITH: -1
WEAPONSMITH: -1
WANDERING_TRADER: -1